### ISSUE TITLE
ADV/Crit Modifier Key brings up "Crit/Normal" prompt on damage rolls rather than skipping prompt and rolling critical damage

### ISSUE THREAD

**Issue by alaustin0** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#26] opened 2022-01-28 14:39 UTC
Setting ADV/Crit Modifier Key to any key (shift, alt, ctrl) and using it + click on a damage roll does not auto roll critical damage, rather brings up the "Crit/Normal" prompt.

See Discord for conversation: [Here.](https://discord.com/channels/170995199584108546/670336046164213761/936625861090738196)

**Comment by akrigline** [comment] 2022-01-28 14:40
Caused by #22
Can you share a screenshot of your settings and the item configuration @alaustin0 ?

**Comment by alaustin0** [comment] 2022-01-28 14:41
Yep, just caught your message right after I submitted. Defaults on a fresh world.
<img width="582" alt="Screen Shot 2022-01-28 at 9 28 02 AM" src="https://user-images.githubusercontent.com/97931877/151566183-5cd7bc03-1f26-4443-ac14-e40a975b4fa2.png">

**Comment by akrigline** [comment] 2022-01-30 17:23
Fixed with 3.2.7

**Closed** 2022-01-30 17:22 UTC
Labels: bug
