### ISSUE TITLE
Bonuses to damage rolls add onto each roll instead of each formula group.

### ISSUE THREAD

**Issue by krbz999** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#36] opened 2022-04-06 09:47 UTC
If a character has, e.g., "+1d6" to `mwak.damage` and a weapon with a formula group with two formulas, they receive the bonus twice. Is this intended behavior?

![Screenshot 2022-04-06 114509](https://user-images.githubusercontent.com/50169243/161947391-0eb6069e-dd34-4fe2-b1bd-5346977b2c03.png)

**Comment by akrigline** [comment] 2022-04-08 17:47
This doesn't seem like intended behavior, but at the same time I'm not 100% sure how to change the behavior in such a way that it makes sense.

Ideally the bonus would be applied once, but how do we determine which damage part to apply it to?
Feels like there needs to be a separate UI element to allow toggling which damage parts get the bonus damage?

Tricky tricky. Not sure how to proceed on this.

**Comment by krbz999** [comment] 2022-04-08 17:55
I feel like a good temporary workaround is to default to applying it only to the first formula - or no formulas and only the total (less ideal since that is toggleable, and not sure if it is even possible).

**Comment by akrigline** [comment] 2022-04-08 19:05
Yeah only the total isn't super possible. Adding a whole other damage part with just effects is an idea. Might even be able to give them a label based on the effect name.

**Comment by krbz999** [comment] 2022-04-08 21:32
How are you imagining it would work or look with multiple additional damage effects?

**Comment by PaulWRoberts** [comment] 2022-04-17 20:45
I think it just applying the effect to the first in the group makes sense. Mods which do not create groups (better rolls, midi) but split out the damage just add it to the first.

**Comment by akrigline** [comment] 2022-04-23 19:43
I took a look at this problem today and I'm afraid it's going to become a Wontfix.
This extra damage is added in the core 5e's `Item5e#damageRoll` method as the "actorBonus" part of the damage formula.

That method accomplishes a lot of other things (e.g. spell scaling, ammo bonus damage, crit calculations) and we rely on it for those things rather than remaking all of that logic ourself (which would be less maintainable).

Unfortunately this means there's some inherent undesired behavior as each damage part is run individually through this method (`_rollDamageParts` in `item-damage-patch.mjs`):
- Actor Special Trait damage bonuses (including those from active effects) are applied to each damage part.
- Spell scaling applies to each individual damage part, instead of the spell overall ("wrong" for spells like Flame Strike and Ice Knife, desired for spells like Toll the Dead).

I cannot see a clean way to work around this limitation with the way the current system handles damage rolls, so this is going to be something you'll have to be aware of and account for.

I'm open to seeing PRs which aim to fix this problem.

**Comment by PaulWRoberts** [comment] 2022-04-24 19:22
I looked into this and if dice damageRoll were patchable then it would be a simple matter of wrapping that method to evaluate the parts individually rather than on item damageRoll. However, for some reason I cannot fathom that method cannot be patched as its descriptor is explicitly configurable = false.

I have to agree that this cannot be fixed without overwriting item.damageRoll, rather than just wrapping it. Which I can understand goes against the intent of this module. I would recommend then that the feature of separating the damage parts on the damage card be removed as it does not function as expected.

**Comment by akrigline** [comment] 2022-04-24 22:18
Certainly won't be removing the feature just because of this.

Spitballing. Wonder if it is smart to only use the wrapped item damage roll for the first formula in the relevant damage parts, and directly call the lower level damageRoll with the other parts.

That would get around this problem while keeping spell scaling predicable (it's always the first part of the parts chosen in the damage group being rolled)

**Comment by PaulWRoberts** [comment] 2022-04-25 19:41
I like that idea. My fear is that it is too much like rewriting dnd5e attack logic, and I love that this module does not do that. But I think this is a solid approach to the problem.
So, thinking this through you end up with the following applied to the first part of the attack:
1/ Spell scaling
2/ Ammo bonus (which is great, because currently you will consume as much ammo as there are parts of the attack)
3/ Character damage bonuses (I kind of wish this was a separate part because it can be a different damage type)
4/ Crit damage bonus (I believe this should be once only, so makes sense)
5/ While it handles the damage bonus dialog, MRE overrides this. Maybe it does not need to be after this change though, which would simplify the code somewhat.

And the overhead would be that MRE will need to fill out the attack options for each part after the first.

**Comment by akrigline** [comment] 2022-04-26 00:29
v4 alpha 1 can be tested with this change:

https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/releases/tag/4.0.0a

manifest:
```
https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/releases/download/4.0.0a/module.json
```

**Comment by PaulWRoberts** [comment] 2022-04-26 04:21
My testing so far is showing that this is working as expected with applying upcast spell damage, active effect bonus and extra critical damage from my weapon to the first roll only. So far nothing weird has happened. But I will keep playing with this and let you know if anything else comes up.

**Closed** 2022-05-14 16:05 UTC
Labels: bug, enhancement
